name: CI/CD Pipeline

on:

  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:

  ci:

    if: github.event_name == 'pull_request'

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Application Test
        run: node app.js & sleep 5

      - name: Build Docker Image
        run: docker build -t cicd-demo .

  cd:

    if: github.event_name == 'push'

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker Image
        run: docker build -t ghcr.io/${{ github.repository }}/cicd-demo:latest .

      - name: Push Docker Image
        run: docker push ghcr.io/${{ github.repository }}/cicd-demo:latest